print("Welcome to The Calculator!")
num1=input("Please type first number: ")
operation=input("Please select operation: ")
num2=input("Please type second number: ")
if(operation=="+"):print(int(num1) + int(num2))
if(operation=="-"):print(int(num1) - int(num2))
if(operation=="*"):print(int(num1) * int(num2))
if(operation=="/"):print(int(num1) / int(num2))
if(operation=="*"):print(int(num1) ** int(num2))
if(operation=="%"):print(int(num1) % int(num2))
if(operation=="//"):print(int(num1) // int(num2))